# Generated by Django 4.2.3 on 2024-04-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('max_time', models.IntegerField(verbose_name='Maximum Time (seconds)')),
                ('last_movement_time', models.DateTimeField(auto_now=True, verbose_name='Last Movement Time')),
                ('white_player_time', models.IntegerField(default=0, verbose_name='White PLayer Time (seconds)')),
                ('black_player_time', models.IntegerField(default=0, verbose_name='White PLayer Time (seconds)')),
                ('destroyed_pieces', models.JSONField(default=list, verbose_name='Destroyed Pieces')),
                ('destroyed_white_pieces', models.JSONField(default=list, verbose_name='Destroyed White Pieces')),
                ('destroyed_black_pieces', models.JSONField(default=list, verbose_name='Destroyed Black Pieces')),
                ('movements', models.JSONField(default=[[['Rook black', 'Knight black', 'Bishop black', 'King black', 'Queen black', 'Bishop black', 'Knight black', 'Rook black'], ['Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black'], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white'], ['Rook white', 'Knight white', 'Bishop white', 'King white', 'Queen white', 'Bishop white', 'Knight white', 'Rook white']]], verbose_name='movements')),
                ('playing', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_player_games', to=settings.AUTH_USER_MODEL, verbose_name='Black Player')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_player_games', to=settings.AUTH_USER_MODEL, verbose_name='White Player')),
            ],
        ),
    ]
