# Generated by Django 4.2.3 on 2024-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_time',
            field=models.IntegerField(default=900, verbose_name='Maximum Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='movements',
            field=models.JSONField(default=[[['Rook black', 'Knight black', 'Bishop black', 'Queen black', 'King black', 'Bishop black', 'Knight black', 'Rook black'], ['Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black', 'Pawn black'], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', ''], ['Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white', 'Pawn white'], ['Rook white', 'Knight white', 'Bishop white', 'Queen white', 'King white', 'Bishop white', 'Knight white', 'Rook white']]], verbose_name='movements'),
        ),
    ]
