# Generated by Django 4.2.3 on 2024-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_max_time_alter_game_movements'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_player_score',
            field=models.IntegerField(default=0, verbose_name='White PLayer Score'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player_score',
            field=models.IntegerField(default=0, verbose_name='White PLayer Score'),
        ),
    ]
