# Generated by Django 4.2.3 on 2024-04-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_black_player_score_game_white_player_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='destroyed_black_pieces',
        ),
        migrations.RemoveField(
            model_name='game',
            name='destroyed_white_pieces',
        ),
        migrations.AddField(
            model_name='game',
            name='end_reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
