# Generated by Django 4.2.3 on 2024-05-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_remove_game_destroyed_black_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='game',
            name='black_player_time',
            field=models.IntegerField(default=0, verbose_name='White PLayer Time (seconds)  '),
        ),
    ]
