# Generated by Django 4.2.3 on 2024-05-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
