# Generated by Django 4.2.3 on 2023-11-17 15:22

import AUTH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0003_user_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', upload_to=AUTH.models.ModelUtils.avatar_filename),
        ),
    ]
