# Generated by Django 4.2.3 on 2024-04-14 14:18

import AUTH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', upload_to=AUTH.models.ModelUtils.avatar_filename, verbose_name='Avatar Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
    ]
