# Generated by Django 4.2.3 on 2024-04-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0005_remove_user_followers_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_score',
            field=models.IntegerField(default=0, verbose_name='Global Score'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
    ]
