# Generated by Django 4.2.3 on 2024-05-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0006_user_global_score_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
