# Generated by Django 4.2.3 on 2024-06-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0007_remove_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
